CREATE TABLE person ( person_id SERIAL PRIMARY KEY, name  VARCHAR(30) NOT NULL, age INTEGER NOT NULL, height FLOAT NOT NULL, city VARCHAR(30) NOT NULL , favorite_color VARCHAR(15) NOT NULL );
INSERT INTO person (name, age, height, city, favorite_color) VALUES('bob', 31, 168, 'Glendale', 'orange'),('steve', 27, 159, 'Orlando', 'red'),('Maria', 23, 125,'Berlin', 'blue' ),('Bessy', 42, 162, 'San Antonio', 'orange'),('Caleb', 53, 198, 'Scottsdale', 'black');
SELECT * FROM person ORDER BY height DESC;
SELECT * FROM person ORDER BY height ASC;
SELECT * FROM person ORDER BY age DESC;
SELECT * FROM person WHERE age > 20;
SELECT * FROM person WHERE age = 18;
SELECT * FROM person WHERE age < 18 OR age > 30;
SELECT * FROM person WHERE age != 27;
SELECT * FROM person WHERE favorite_color != 'red';
SELECT * FROM person WHERE favorite_color != 'red' OR favorite_color != 'blue';
SELECT * FROM person WHERE favorite_color = 'orange' OR favorite_color = 'green';
SELECT * FROM person WHERE favorite_color IN ('orange', 'green', 'blue');
SELECT * FROM person WHERE favorite_color IN ('yellow', 'purple');